function plottemplate3p(X1, Y1, X2, Y2, X3, Y3)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 03-May-2021 11:29:32

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','CMT Mod','LineWidth',1,'Color',[0 0 1]);

% Create plot
plot(X2,Y2,'DisplayName','REF Exp','LineWidth',1,'Color',[1 0 0]);

% Create plot
plot(X3,Y3,'DisplayName','REF Mod','LineWidth',1,...
    'Color',[0.149019607843137 0.149019607843137 0.149019607843137]);

% Create ylabel
ylabel('Temperature [ºC]');

% Create xlabel
xlabel({'Time[s]',''});

% Create title
title('Air temperature in the cabin');

box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',14);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.2155952344849 0.706115331652802 0.242500003610339 0.188688217143142]);

